/**
 * @file move_to_point.cpp
 * @brief Move the arm to the visually detected point (C++ version).
 *
 * Subscribes to /vision/detected_point (PointStamped in base_link published
 * by mycobot_vision_tutorial/color_detector), then plans and executes a
 * motion that hovers the end effector above that point.
 *
 * Same MoveGroupInterface pattern as mycobot_moveit_demos/hello_moveit.
 * The MoveIt config is injected through the MYCOBOT_VISION_MOVEIT_PARAMS
 * environment variable (path to a clean params yaml generated by the launch
 * file) because launch-generated parameter files trip over !!python/tuple
 * tags and stray --ros-args sections.
 */

#include <array>
#include <cstdlib>
#include <memory>
#include <thread>
#include <vector>

#include <geometry_msgs/msg/point_stamped.hpp>
#include <geometry_msgs/msg/pose_stamped.hpp>
#include <moveit/move_group_interface/move_group_interface.hpp>
#include <rclcpp/rclcpp.hpp>

using namespace std::chrono_literals;

class MoveToPointNode : public rclcpp::Node
{
public:
  MoveToPointNode()
  : Node("move_to_point")
  {
    approach_height_ = declare_parameter<double>("approach_height", 0.03);
    single_shot_ = declare_parameter<bool>("single_shot", true);
    quat_ = {
      declare_parameter<double>("goal_qx", 1.0),   // tool-down orientation,
      declare_parameter<double>("goal_qy", 0.0),   // same as mycobot demos
      declare_parameter<double>("goal_qz", 0.0),
      declare_parameter<double>("goal_qw", 0.0)};

    sub_ = create_subscription<geometry_msgs::msg::PointStamped>(
      "/vision/detected_point", 10,
      [this](geometry_msgs::msg::PointStamped::SharedPtr msg) {
        latest_ = *msg;
        has_new_ = true;
      });

    RCLCPP_INFO(
      get_logger(),
      "waiting for /vision/detected_point, will hover %.2f m above it",
      approach_height_);
  }

  bool pop_target(geometry_msgs::msg::PointStamped & out)
  {
    if (!has_new_) {
      return false;
    }
    out = latest_;
    has_new_ = false;
    return true;
  }

  double approach_height() const { return approach_height_; }
  bool single_shot() const { return single_shot_; }
  const std::array<double, 4> & quat() const { return quat_; }

private:
  double approach_height_;
  bool single_shot_;
  std::array<double, 4> quat_;
  geometry_msgs::msg::PointStamped latest_;
  bool has_new_{false};
  rclcpp::Subscription<geometry_msgs::msg::PointStamped>::SharedPtr sub_;
};

int main(int argc, char ** argv)
{
  // Inject the clean params file (if any) before rclcpp parses the arguments,
  // so the node picks up the full MoveIt config regardless of raw argv quirks.
  std::vector<std::string> extra_args;
  if (const char * params_file = std::getenv("MYCOBOT_VISION_MOVEIT_PARAMS")) {
    extra_args = {"--ros-args", "--params-file", params_file};
  }
  std::vector<char *> arg_vec;
  arg_vec.push_back(argv[0]);
  for (auto & a : extra_args) {
    arg_vec.push_back(a.data());
  }
  for (int i = 1; i < argc; ++i) {
    arg_vec.push_back(argv[i]);
  }
  rclcpp::init(static_cast<int>(arg_vec.size()), arg_vec.data());

  auto node = std::make_shared<MoveToPointNode>();
  rclcpp::executors::SingleThreadedExecutor executor;
  executor.add_node(node);
  std::thread spinner([&executor]() { executor.spin(); });

  using moveit::planning_interface::MoveGroupInterface;
  auto arm = MoveGroupInterface(node, "arm");
  arm.setPlanningPipelineId("ompl");
  arm.setPlannerId("RRTConnectkConfigDefault");
  arm.setPlanningTime(5.0);
  arm.setMaxVelocityScalingFactor(0.3);
  arm.setMaxAccelerationScalingFactor(0.3);

  geometry_msgs::msg::PointStamped target;
  bool has_moved = false;

  while (rclcpp::ok()) {
    if (!node->pop_target(target)) {
      std::this_thread::sleep_for(200ms);
      continue;
    }
    if (node->single_shot() && has_moved) {
      break;
    }

    geometry_msgs::msg::PoseStamped goal;
    goal.header.frame_id = "base_link";
    goal.header.stamp = node->now();
    goal.pose.position.x = target.point.x;
    goal.pose.position.y = target.point.y;
    goal.pose.position.z = target.point.z + node->approach_height();
    const auto & q = node->quat();
    goal.pose.orientation.x = q[0];
    goal.pose.orientation.y = q[1];
    goal.pose.orientation.z = q[2];
    goal.pose.orientation.w = q[3];

    RCLCPP_INFO(
      node->get_logger(), "planning to (%.3f, %.3f, %.3f)",
      goal.pose.position.x, goal.pose.position.y, goal.pose.position.z);

    arm.setStartStateToCurrentState();
    arm.setPoseTarget(goal);

    MoveGroupInterface::Plan plan;
    if (arm.plan(plan) != moveit::core::MoveItErrorCode::SUCCESS) {
      RCLCPP_WARN(
        node->get_logger(),
        "planning failed, is the point reachable? (keep the object 15-20 cm "
        "in front of the arm, measured horizontally)");
      std::this_thread::sleep_for(2s);  // cooldown before the next attempt
      continue;
    }
    if (arm.execute(plan) != moveit::core::MoveItErrorCode::SUCCESS) {
      RCLCPP_WARN(node->get_logger(), "execution failed");
      continue;
    }

    has_moved = true;
    RCLCPP_INFO(
      node->get_logger(), "motion executed, arm is hovering above the target");
  }

  // MoveGroupInterface's action calls do not react to shutdown while pending,
  // so a strict join here can hang on Ctrl+C; detach and let the process exit.
  executor.cancel();
  spinner.detach();
  rclcpp::shutdown();
  return 0;
}
